[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
pump_fees_to_jupiter_perps = "FjDSgr7sF8o3rwqnSp9m87xjEX18XxgWELhNVxwVkjDz"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "npm run test:ts"
